### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by JeffreyCA** [JeffreyCA/PRESTO-Wallet#5]
- [x] Implement filter dialog in Transactions tab
- [x] Support for month bar
- [x] Home/Balances screen (stub data)
- [x] Web-scraping for balances and transaction data
- [x] Handle Login -> Dashboard transition
- [ ] Show number of transaction in nav bar of Transactions page

- [ ] Settings
- [ ] Multiple cards

- [ ] Make Home screen wallet picker, like [this](https://www.file-extensions.org/imgs/app-picture/9251/apple-passbook.png)
